// ============================================================
// THE WEB OF COMPUTATION — topic depth (edit me)
// One entry per topic, keyed "fieldId|topic name" exactly as in data.js.
//   i    the idea, in plain words
//   s    the story: who, when, how it happened
//   n    why it matters now
//   src  [title, url] — a primary source or the best way in
// Read by extras.js, which adds a "deeper" drawer to every topic card
// and opens the full entry when a topic is clicked on the map.
// ============================================================
const TOPIC_DETAIL = {

// ---------------- Mathematical Logic ----------------
"logic|Boolean algebra":{ i:"Logic written as algebra: true and false become 1 and 0, 'and' becomes multiplication, 'or' a kind of addition. Arguments can then be checked by calculation instead of by rhetoric.",
  s:"George Boole, a largely self-taught schoolmaster's son, published The Mathematical Analysis of Logic in 1847 and The Laws of Thought in 1854. For ninety years it was a curiosity for logicians.",
  n:"In 1937 Shannon showed Boolean algebra describes switching circuits exactly. Every processor since is Boole's algebra etched in silicon.", src:["Boole — An Investigation of the Laws of Thought (1854)", "https://www.gutenberg.org/ebooks/15114"] },
"logic|Predicate logic":{ i:"Logic that can talk about objects and their properties with variables and quantifiers: 'for every x', 'there exists an x'. It is expressive enough to formalise almost all of mathematics.",
  s:"Gottlob Frege's Begriffsschrift (1879) introduced quantifiers and a fully formal notation. Bertrand Russell found a paradox in Frege's later system in 1902, just as its second volume went to press.",
  n:"Predicate logic underlies database query languages, program verification, and the specification languages used to check chips and software.", src:["Stanford Encyclopedia of Philosophy — Frege's Logic", "https://plato.stanford.edu/entries/frege-logic/"] },
"logic|Gödel incompleteness":{ i:"Any consistent formal system strong enough for arithmetic contains true statements it cannot prove, and cannot prove its own consistency.",
  s:"Kurt Gödel, aged 25, announced the result in Königsberg in 1930 and published it in 1931, ending David Hilbert's programme to put all of mathematics on a complete, provably consistent footing.",
  n:"Gödel's self-reference trick became Turing's proof that the halting problem is undecidable, and it still sets the limits of what any automated reasoner, human-built or learned, can prove.", src:["Gödel (1931) — Über formal unentscheidbare Sätze", "https://doi.org/10.1007/BF01700692"] },
"logic|λ-calculus":{ i:"A tiny language with only functions: define one (λx. body) and apply one to an argument. Numbers, booleans and recursion can all be encoded inside it.",
  s:"Alonzo Church developed it in the early 1930s as a foundation for logic. In 1936 he used it to show that some problems cannot be decided, weeks before Turing reached the same result with his machines.",
  n:"It is the direct ancestor of LISP, Haskell and every language with anonymous functions ('lambdas'), and the basis of type theory and proof assistants.", src:["Stanford Encyclopedia of Philosophy — The Lambda Calculus", "https://plato.stanford.edu/entries/lambda-calculus/"] },

// ---------------- Computability ----------------
"computability|Turing machine":{ i:"An idealised clerk with an endless paper tape, a pencil and a finite rule table. At each step it reads one symbol, writes one, moves left or right and changes state. That is all, and it is enough to compute anything computable.",
  s:"Alan Turing, 24, described it in 'On Computable Numbers' (1936) to give a precise meaning to 'mechanical procedure', answering Hilbert's decision problem.",
  n:"It remains the standard definition of 'algorithm', and 'Turing-complete' is how we say a language or system can compute anything a computer can.", src:["Turing (1936) — On Computable Numbers", "https://doi.org/10.1112/plms/s2-42.1.230"] },
"computability|Universal Turing machine":{ i:"One machine that, given a description of any other machine on its tape, simulates it. Programs are just data, and one piece of hardware can be every computer.",
  s:"Turing included it in the same 1936 paper. Von Neumann's 1945 stored-program design made the idea physical: instructions live in memory alongside data.",
  n:"Every general-purpose computer, phone and cloud server is a universal machine; emulators and virtual machines are the idea used literally.", src:["Stanford Encyclopedia of Philosophy — Turing Machines", "https://plato.stanford.edu/entries/turing-machine/"] },
"computability|Halting problem":{ i:"No program can decide, for every program and input, whether it will eventually stop. Assume such a decider exists, feed it a program built to do the opposite of whatever it predicts, and you get a contradiction.",
  s:"Turing proved it in 1936 with a diagonal argument descended from Cantor and Gödel. It was the first natural problem shown to be unsolvable by any algorithm.",
  n:"It is why no tool can find every bug or prove every program correct, and why static analysers and AI code checkers must sometimes answer 'don't know'.", src:["Turing (1936) — On Computable Numbers", "https://doi.org/10.1112/plms/s2-42.1.230"] },
"computability|Church–Turing thesis":{ i:"Anything that can be computed by any mechanical procedure can be computed by a Turing machine. It is a claim about the world, not a theorem, so it can't be proved, only tested.",
  s:"Church (λ-calculus), Turing (machines) and Kleene (recursive functions) proposed three very different definitions in 1936; all turned out to compute exactly the same things.",
  n:"No physical computer, quantum ones included, has computed anything a Turing machine cannot; quantum computers only change how fast some things can be done.", src:["Stanford Encyclopedia of Philosophy — The Church–Turing Thesis", "https://plato.stanford.edu/entries/church-turing/"] },

// ---------------- Automata ----------------
"automata|McCulloch–Pitts neuron":{ i:"A neuron modelled as a threshold switch: it fires if enough excitatory inputs are on and no inhibitory input is. Networks of them compute logical functions, and networks with loops have memory.",
  s:"McCulloch and Pitts's 1943 paper inspired Stephen Kleene, who in 1951 characterised exactly which patterns such nets can recognise, founding finite automata theory.",
  n:"The same paper is the root of both neural networks and automata theory, which is why the node appears twice on the map.", src:["McCulloch & Pitts (1943)", "https://doi.org/10.1007/BF02478259"] },
"automata|Finite automata / regex":{ i:"A machine with finitely many states and no memory beyond them, reading input one symbol at a time. Regular expressions describe exactly the patterns such machines recognise.",
  s:"Kleene introduced regular expressions in 1951 (published 1956). Ken Thompson built them into the QED and ed text editors in the 1960s, and from there into grep and Unix.",
  n:"Every search box, form validator, lexer and log filter uses regular expressions or finite automata.", src:["Kleene (1956) — Representation of Events in Nerve Nets and Finite Automata", "https://doi.org/10.1515/9781400882618-002"] },
"automata|Chomsky hierarchy":{ i:"A ladder of grammars, each more powerful than the last: regular, context-free, context-sensitive and unrestricted, matched to finite automata, pushdown automata, linear-bounded automata and Turing machines.",
  s:"Linguist Noam Chomsky proposed it in 1956 to study human language. Computer scientists adopted context-free grammars to define programming languages (ALGOL 60's BNF).",
  n:"Parsers for every programming language are built on context-free grammars, and researchers probe whether transformers can learn languages at each level of the hierarchy.", src:["Chomsky (1956) — Three Models for the Description of Language", "https://doi.org/10.1109/TIT.1956.1056813"] },

// ---------------- Complexity ----------------
"complexity|P vs NP":{ i:"P is the problems a computer can solve quickly; NP is the problems whose solutions can be checked quickly. Is every quickly checkable problem also quickly solvable? Almost everyone thinks not; nobody has proved it.",
  s:"Stephen Cook (1971) and Leonid Levin (independently, in the USSR) formalised the question. Gödel had asked a version of it in a 1956 letter to von Neumann.",
  n:"It is one of the seven Clay Millennium Prize problems ($1 million). Modern cryptography depends on some NP problems being hard.", src:["Cook (1971) — The Complexity of Theorem-Proving Procedures", "https://doi.org/10.1145/800157.805047"] },
"complexity|NP-completeness":{ i:"The hardest problems in NP: if any one of them had a fast algorithm, every NP problem would. Thousands of practical problems (scheduling, routing, packing) turn out to be NP-complete.",
  s:"Cook showed Boolean satisfiability (SAT) is NP-complete in 1971. In 1972 Richard Karp showed 21 classic combinatorial problems are too, making the concept central to computer science.",
  n:"Knowing a problem is NP-complete tells engineers to use heuristics or approximations. Modern SAT solvers nonetheless handle huge industrial instances.", src:["Karp (1972) — Reducibility Among Combinatorial Problems", "https://doi.org/10.1007/978-1-4684-2001-2_9"] },
"complexity|Randomized complexity":{ i:"Algorithms allowed to flip coins, accepting a tiny chance of error in exchange for speed. For some problems randomness seemed to help enormously.",
  s:"Solovay and Strassen (1977) and Rabin (1980) gave fast randomised tests for whether a number is prime. In 2002 Agrawal, Kayal and Saxena found a deterministic polynomial test (AKS), showing randomness wasn't strictly needed there.",
  n:"Randomised primality tests generate the keys that secure web traffic, and randomness drives hashing, sampling and stochastic gradient descent.", src:["Agrawal, Kayal & Saxena (2004) — PRIMES is in P", "https://doi.org/10.4007/annals.2004.160.781"] },

// ---------------- Quantum ----------------
"quantum|Qubits & gates":{ i:"A qubit can be in a superposition of 0 and 1; many qubits can be entangled. Quantum gates rotate these states, and interference amplifies right answers while cancelling wrong ones.",
  s:"Richard Feynman suggested quantum computers for simulating physics in 1981; David Deutsch defined a universal quantum computer in 1985.",
  n:"Machines from IBM, Google, Quantinuum and others now have from dozens to about a thousand physical qubits, still too noisy for most useful algorithms.", src:["Deutsch (1985) — Quantum Theory, the Church–Turing Principle and the Universal Quantum Computer", "https://doi.org/10.1098/rspa.1985.0070"] },
"quantum|Shor's algorithm":{ i:"A quantum algorithm that factors large numbers exponentially faster than any known classical method, by finding the period of a function with the quantum Fourier transform.",
  s:"Peter Shor, at Bell Labs, found it in 1994. It turned quantum computing from a physics curiosity into a national-security concern overnight.",
  n:"A large, error-corrected quantum computer would break RSA and elliptic-curve cryptography, which is why the world is migrating to post-quantum cryptography.", src:["Shor (1997) — Polynomial-Time Algorithms for Prime Factorization and Discrete Logarithms", "https://doi.org/10.1137/S0097539795293172"] },
"quantum|Quantum error correction":{ i:"Qubits are fragile, and measuring them destroys superpositions. Error correction spreads one 'logical' qubit over many physical ones so errors can be detected and fixed without looking at the data directly.",
  s:"Shor (1995) and Andrew Steane (1996) found the first quantum error-correcting codes, overturning the belief that quantum computation was hopelessly fragile.",
  n:"In 2024 Google reported logical qubits whose error rate fell as the code grew, the long-sought 'below threshold' milestone.", src:["Shor (1995) — Scheme for Reducing Decoherence in Quantum Computer Memory", "https://doi.org/10.1103/PhysRevA.52.R2493"] },

// ---------------- Mechanical era ----------------
"mech|Difference Engine":{ i:"A machine of gears and columns that tabulates polynomials by repeated addition (the method of finite differences), removing human error from printed mathematical tables.",
  s:"Babbage proposed it in 1822, frustrated by errors in navigation tables. The government funded it for years; it was never finished. The Science Museum built Difference Engine No. 2 from his drawings in 1991, and it worked.",
  n:"The finished engine, with its printer, stands in London's Science Museum and a second copy was built for Nathan Myhrvold.", src:["Science Museum — Babbage's Difference Engine No. 2", "https://collection.sciencemuseumgroup.org.uk/objects/co526657/babbages-difference-engine-no-2-1847-1849-difference-engine"] },
"mech|Analytical Engine":{ i:"A general-purpose mechanical computer design, with a 'mill' (processor), a 'store' (memory), conditional branching and programs on punched cards borrowed from the Jacquard loom.",
  s:"Babbage designed it from 1837 until his death in 1871. It was never built, though his son Henry assembled part of the mill.",
  n:"It contained almost every element of a modern computer a century before electronics, and the Plan 28 project is working toward building one.", src:["Menabrea & Lovelace — Sketch of the Analytical Engine (1843)", "https://www.fourmilab.ch/babbage/sketch.html"] },
"mech|Note G — the first program":{ i:"A step-by-step table of operations for computing Bernoulli numbers on the Analytical Engine, with loops and variables: widely called the first published computer program.",
  s:"Ada Lovelace wrote it in 1843 as the last of her notes on Menabrea's paper. Historians debate how much Babbage contributed, but the vision that the Engine could manipulate any symbols was hers.",
  n:"The programming language Ada is named after her, and Ada Lovelace Day celebrates women in science each October.", src:["Lovelace — Note G", "https://www.fourmilab.ch/babbage/sketch.html"] },

// ---------------- Electromechanical & wartime ----------------
"wartime|Shannon's master's thesis":{ i:"Relay and switching circuits obey Boolean algebra exactly, so circuits can be designed and simplified with algebra instead of trial and error.",
  s:"Claude Shannon, 21, wrote 'A Symbolic Analysis of Relay and Switching Circuits' at MIT in 1937, after working on Vannevar Bush's differential analyser. It has been called the most important master's thesis of the century.",
  n:"Digital circuit design begins here: every chip is designed by manipulating Boolean expressions.", src:["Shannon (1938) — A Symbolic Analysis of Relay and Switching Circuits", "https://doi.org/10.1109/T-AIEE.1938.5057767"] },
"wartime|Zuse Z3":{ i:"The first working programmable, fully automatic digital computer, built from about 2,600 telephone relays and using binary floating-point arithmetic.",
  s:"Konrad Zuse completed it in Berlin in 1941, largely on his own. It was destroyed in an Allied bombing raid in 1943; a replica is in the Deutsches Museum.",
  n:"Zuse also designed Plankalkül (1945), arguably the first high-level programming language, published only in 1972.", src:["Deutsches Museum — Konrad Zuse's Z3 (replica)", "https://www.deutsches-museum.de/"] },
"wartime|The Bombe":{ i:"An electromechanical machine that tested thousands of possible Enigma settings per minute, using a 'crib' (a guessed piece of plaintext) to rule most of them out by logical contradiction.",
  s:"Turing designed it in 1939 building on the Polish bomba of Marian Rejewski; Gordon Welchman added the diagonal board. Over 200 were built and operated, largely by members of the Women's Royal Naval Service.",
  n:"A working reconstruction runs at the National Museum of Computing at Bletchley Park.", src:["National Museum of Computing — the Turing–Welchman Bombe", "https://www.tnmoc.org/bombe"] },
"wartime|Colossus":{ i:"The first large-scale programmable electronic digital computer, with about 2,500 valves, built to break the German Lorenz teleprinter cipher by statistical counting.",
  s:"Post Office engineer Tommy Flowers built it in 1943–44, partly with his own money after officials doubted valves could be reliable. Ten were in use by the war's end; its existence stayed secret until the 1970s.",
  n:"Because of the secrecy, ENIAC was long credited as the first electronic computer. A rebuilt Colossus runs at Bletchley Park.", src:["National Museum of Computing — Colossus", "https://www.tnmoc.org/colossus"] },
"wartime|ENIAC":{ i:"A general-purpose electronic computer with about 18,000 vacuum tubes, calculating ballistics tables thousands of times faster than people with desk calculators.",
  s:"J. Presper Eckert and John Mauchly built it at the University of Pennsylvania (1943–1945). Six women (Jean Bartik, Betty Holberton, Kathleen Antonelli, Marlyn Meltzer, Frances Spence and Ruth Teitelbaum) programmed it by rewiring panels.",
  n:"The ENIAC programmers were barely acknowledged for decades; their story is now a staple of computing history.", src:["Penn Engineering — ENIAC", "https://www.seas.upenn.edu/about/history-heritage/eniac/"] },

// ---------------- Stored program ----------------
"stored|von Neumann architecture":{ i:"A computer with one memory holding both instructions and data, a processing unit, and a control unit that fetches and executes instructions in sequence.",
  s:"Von Neumann's 1945 'First Draft of a Report on the EDVAC' described it, drawing on the ENIAC team's ideas; credit is still disputed. Manchester's 'Baby' (1948) ran the first stored program.",
  n:"Nearly every computer is built this way. The 'von Neumann bottleneck' (moving data between memory and processor) is why AI chips put compute next to memory.", src:["von Neumann (1945) — First Draft of a Report on the EDVAC", "https://doi.org/10.1109/85.238389"] },
"stored|The transistor":{ i:"A semiconductor switch and amplifier with no glowing filament: smaller, cooler, faster and far more reliable than a vacuum tube.",
  s:"John Bardeen and Walter Brattain made the point-contact transistor at Bell Labs in December 1947; William Shockley designed the junction transistor soon after. They shared the 1956 Nobel Prize in Physics.",
  n:"A modern chip holds tens of billions of transistors; it is the most manufactured object in human history.", src:["Nobel Prize — Physics 1956", "https://www.nobelprize.org/prizes/physics/1956/summary/"] },
"stored|Integrated circuit":{ i:"Many transistors and their wiring made together on one piece of semiconductor, instead of being soldered by hand.",
  s:"Jack Kilby at Texas Instruments (1958, germanium) and Robert Noyce at Fairchild (1959, silicon with planar wiring) invented it independently. Kilby received the 2000 Nobel Prize; Noyce had died in 1990.",
  n:"The Apollo Guidance Computer was an early big customer. Today's chips are made with extreme-ultraviolet lithography at features of a few nanometres.", src:["Nobel Prize — Physics 2000 (Kilby)", "https://www.nobelprize.org/prizes/physics/2000/kilby/facts/"] },
"stored|Moore's law":{ i:"The number of transistors on a chip doubles roughly every two years. It was an observation about economics and engineering, not a law of nature.",
  s:"Gordon Moore wrote in 1965 that components per chip were doubling yearly; he revised it to every two years in 1975. It held remarkably well for about five decades.",
  n:"Doubling has slowed as transistors approach atomic sizes, and progress now comes from 3-D stacking, chiplets and specialised AI hardware.", src:["Moore (1965) — Cramming More Components onto Integrated Circuits", "https://doi.org/10.1109/JPROC.1998.658762"] },

// ---------------- AI-era hardware ----------------
"aihw|Microprocessor (Intel 4004)":{ i:"A whole central processing unit on a single chip: 2,300 transistors, 4-bit words, about 92,000 instructions per second.",
  s:"Federico Faggin, Ted Hoff, Stanley Mazor and Masatoshi Shima designed it at Intel in 1971 for a Japanese calculator company, Busicom. Faggin signed his initials on the chip.",
  n:"It began the path to personal computers, phones and every embedded controller.", src:["Intel — the 4004", "https://www.intel.com/content/www/us/en/history/museum-story-of-intel-4004.html"] },
"aihw|GPU + CUDA":{ i:"Graphics processors run thousands of simple operations in parallel. CUDA let programmers use that parallelism for general maths, which neural networks are made of.",
  s:"NVIDIA released CUDA in 2007. In 2012 AlexNet was trained on two gaming GPUs, and deep learning's hardware was settled.",
  n:"NVIDIA's data-centre GPUs train most frontier AI models; demand made it, briefly in 2024, the world's most valuable company.", src:["NVIDIA — CUDA Zone", "https://developer.nvidia.com/cuda-zone"] },
"aihw|TPUs & accelerators":{ i:"Chips designed only for neural-network maths, built around large grids of multiply-accumulate units (systolic arrays) that pass data between neighbours without going back to memory.",
  s:"Google deployed its first Tensor Processing Unit in 2015 and described it in 2017, prompted by estimates that voice search alone would otherwise double its data-centre needs.",
  n:"TPUs, and accelerators from AWS, Meta and many start-ups, now compete with GPUs for training and running AI.", src:["Jouppi et al. (2017) — In-Datacenter Performance Analysis of a Tensor Processing Unit", "https://doi.org/10.1145/3079856.3080246"] },

// ---------------- Design paradigms ----------------
"paradigms|Divide & conquer":{ i:"Split a problem into smaller copies of itself, solve them, and combine the answers. When combining is cheap, the total cost falls dramatically.",
  s:"Von Neumann's merge sort (1945) is an early example; the Fast Fourier Transform (Cooley & Tukey, 1965) is its masterpiece, and Gauss had used the trick around 1805.",
  n:"The FFT runs in every phone, audio codec and MRI scanner; divide and conquer also splits work across thousands of GPUs.", src:["Cooley & Tukey (1965)", "https://doi.org/10.1090/S0025-5718-1965-0178586-1"] },
"paradigms|Dynamic programming":{ i:"Solve each overlapping subproblem once, store the answer in a table, and build up to the whole.",
  s:"Richard Bellman named it at RAND in the early 1950s, choosing a name he said no congressman could object to.",
  n:"DNA alignment, spell checking, speech recognition and the Bellman equation of reinforcement learning are all dynamic programs.", src:["Bellman — Dynamic Programming (1957)", "https://press.princeton.edu/books/paperback/9780691146683/dynamic-programming"] },
"paradigms|Dijkstra / A* search":{ i:"Find shortest paths by always expanding the closest unexplored point; A* adds an estimate of the remaining distance to head for the goal.",
  s:"Dijkstra designed his algorithm in about 20 minutes in 1956 and published it in 1959. Hart, Nilsson and Raphael created A* in 1968 for the SRI robot Shakey.",
  n:"Navigation apps, internet routing and game characters use them constantly.", src:["Dijkstra (1959) — A Note on Two Problems in Connexion with Graphs", "https://doi.org/10.1007/BF01386390"] },
"paradigms|Monte Carlo methods":{ i:"Answer hard questions by simulating random samples and averaging. The error shrinks like one over the square root of the number of samples, whatever the dimension.",
  s:"Stanislaw Ulam conceived it in 1946 while playing solitaire during an illness; von Neumann programmed it on ENIAC for neutron physics; Metropolis named it after the casino.",
  n:"From climate and finance to film rendering, Bayesian statistics and AlphaGo's tree search, Monte Carlo is everywhere.", src:["Metropolis & Ulam (1949) — The Monte Carlo Method", "https://doi.org/10.1080/01621459.1949.10483310"] },

// ---------------- Data structures ----------------
"structs|Hash tables":{ i:"Compute where an item lives from its key, instead of searching for it: lookup, insert and delete in constant time on average.",
  s:"Hans Peter Luhn at IBM described hashing in a 1953 internal memo; Gene Amdahl and colleagues used open addressing around the same time.",
  n:"Every Python dictionary, JavaScript object, database join and cache uses hashing.", src:["Knuth — The Art of Computer Programming, Vol. 3", "https://www-cs-faculty.stanford.edu/~knuth/taocp.html"] },
"structs|B-trees":{ i:"Balanced search trees whose nodes each hold many keys, sized to a disk page, so even billions of records are only a few reads away.",
  s:"Rudolf Bayer and Edward McCreight invented them at Boeing Research Labs in 1970–72. Nobody is sure what the B stands for; Bayer, Boeing, balanced and broad have all been suggested.",
  n:"Almost every database and file system indexes data with B-trees or B+-trees.", src:["Bayer & McCreight (1972)", "https://doi.org/10.1007/BF00288683"] },
"structs|Heaps & priority queues":{ i:"A tree kept in an array so the smallest item is always on top, with insert and remove-min in logarithmic time.",
  s:"J. W. J. Williams published the binary heap with heapsort in 1964; Robert Floyd improved heap construction the same year.",
  n:"Dijkstra's algorithm, A*, Huffman coding, operating-system schedulers and event simulators all run on priority queues.", src:["Williams (1964) — Algorithm 232: Heapsort", "https://doi.org/10.1145/512274.512284"] },

// ---------------- Analysis of algorithms ----------------
"analysis|Big-O notation":{ i:"A way to describe how an algorithm's cost grows with input size, ignoring constant factors: O(n) grows linearly, O(n²) quadratically, O(log n) barely at all.",
  s:"Paul Bachmann introduced O in number theory in 1894 and Edmund Landau popularised it. Donald Knuth standardised Big-O, Big-Omega and Big-Theta for computer science in 1976.",
  n:"It is the common language for comparing algorithms, and the first tool for asking whether a method will scale to billions of items.", src:["Knuth (1976) — Big Omicron and Big Omega and Big Theta", "https://doi.org/10.1145/1008328.1008329"] },
"analysis|The Art of Computer Programming":{ i:"Knuth's multi-volume treatise analyses algorithms precisely, counting operations exactly and making algorithm analysis a mathematical science.",
  s:"Knuth began it as a single book on compilers in 1962. Volume 1 appeared in 1968; volume 4B in 2022. Frustrated by typesetting, he paused in 1977 to create TeX.",
  n:"It remains the reference for rigorous algorithm analysis; Knuth still pays a reward cheque for every error found.", src:["Donald Knuth — The Art of Computer Programming", "https://www-cs-faculty.stanford.edu/~knuth/taocp.html"] },
"analysis|Numerical linear algebra (BLAS)":{ i:"A standard set of low-level routines for vector and matrix operations, tuned for each processor, so every scientific program gets fast linear algebra for free.",
  s:"Lawson, Hanson, Kincaid and Krogh defined the Level 1 BLAS in 1979; Levels 2 and 3 (matrix–vector and matrix–matrix) followed in 1988–1990. LAPACK was built on them.",
  n:"NumPy, MATLAB and deep learning frameworks call BLAS-style matrix multiplies: the single operation most of AI's compute is spent on.", src:["Lawson et al. (1979) — Basic Linear Algebra Subprograms for Fortran Usage", "https://doi.org/10.1145/355841.355847"] },

// ---------------- Languages ----------------
"langs|Fortran":{ i:"The first widely used high-level language: write formulas and loops, and a compiler produces machine code nearly as fast as a human expert's.",
  s:"John Backus's IBM team released it in 1957 after about three years' work. Within a few years most scientific programming was done in Fortran.",
  n:"Weather, climate and physics codes still run on Fortran, and NumPy relies on Fortran linear algebra libraries.", src:["Backus et al. (1957) — The FORTRAN Automatic Coding System", "https://doi.org/10.1145/1455567.1455599"] },
"langs|LISP":{ i:"A language built from lists and functions in which programs are themselves lists, so programs can easily write and transform programs.",
  s:"John McCarthy designed it in 1958; Steve Russell turned McCarthy's eval into a working interpreter. It became the language of AI research for three decades.",
  n:"Garbage collection, closures and the REPL came from LISP and are now in almost every language.", src:["McCarthy (1960)", "https://doi.org/10.1145/367177.367199"] },
"langs|C":{ i:"A small language close to the hardware, with pointers and manual memory, portable across machines.",
  s:"Dennis Ritchie developed C at Bell Labs around 1972 to rewrite Unix; 'K&R' (1978) spread it everywhere.",
  n:"Operating systems, databases and language runtimes are still written largely in C, though memory-safe Rust is replacing it in places.", src:["Ritchie (1993) — The Development of the C Language", "https://doi.org/10.1145/154766.155580"] },
"langs|Python":{ i:"A readable language that glues together fast libraries written in C, C++, Fortran and CUDA.",
  s:"Guido van Rossum started Python over the Christmas holidays of 1989 and released it in 1991. NumPy (2006), scikit-learn and later PyTorch and TensorFlow made it the language of data and AI.",
  n:"It is the most popular language for machine learning and, by several measures, overall.", src:["Python — history and license", "https://docs.python.org/3/license.html"] },

// ---------------- Compilers ----------------
"compilers|The first compiler (A-0)":{ i:"A program that translates a symbolic description of a program into machine code, so people no longer have to write machine code by hand.",
  s:"Grace Hopper built the A-0 system for the UNIVAC I in 1952 and argued, against much scepticism, for programming in English-like words.",
  n:"Every program runs through a compiler or interpreter descended from this idea.", src:["Hopper (1952) — The Education of a Computer", "https://doi.org/10.1145/609784.609818"] },
"compilers|Curry–Howard correspondence":{ i:"Propositions are types and proofs are programs: a program of type A → B is a proof that A implies B.",
  s:"Haskell Curry noticed it for simple logic in 1934 and 1958; William Howard extended it in a 1969 manuscript published in 1980.",
  n:"It is the foundation of proof assistants such as Coq and Lean, and of richly typed languages.", src:["Wadler (2015) — Propositions as Types", "https://doi.org/10.1145/2699407"] },
"compilers|Proof assistants (Lean, Coq)":{ i:"Software in which you write mathematical proofs that a small, trusted type checker verifies completely.",
  s:"Coq began with Thierry Coquand and Gérard Huet's calculus of constructions (1984–89). Leonardo de Moura started Lean at Microsoft Research in 2013.",
  n:"Coq verified the four-colour theorem and the CompCert C compiler; Lean's mathlib is formalising much of modern mathematics, increasingly with AI help.", src:["Lean — Theorem Proving in Lean 4", "https://lean-lang.org/theorem_proving_in_lean4/"] },

// ---------------- Systems ----------------
"systems|Unix":{ i:"An operating system built from small tools that do one thing well and connect through pipes, with everything treated as a file.",
  s:"Ken Thompson and Dennis Ritchie wrote it at Bell Labs from 1969, on a spare PDP-7; rewriting it in C (1973) made it portable.",
  n:"macOS, iOS, Linux and Android descend from Unix or follow its design.", src:["Ritchie & Thompson (1974) — The UNIX Time-Sharing System", "https://doi.org/10.1145/361011.361061"] },
"systems|Linux + git":{ i:"A free Unix-like kernel developed openly by thousands of people, and a version-control system that stores history as a graph of content hashes.",
  s:"Linus Torvalds announced Linux in 1991 as 'just a hobby'. In 2005 he wrote git in about two weeks after the kernel lost its free version-control licence.",
  n:"Linux runs most servers, all top-500 supercomputers and Android; git (and GitHub) is how most software is built.", src:["Pro Git (free book)", "https://git-scm.com/book/en/v2"] },
"systems|MapReduce → Spark":{ i:"Process huge datasets on thousands of machines by writing just a map function and a reduce function; the system handles distribution and failures.",
  s:"Jeffrey Dean and Sanjay Ghemawat described MapReduce at Google in 2004; Hadoop copied it, and Spark (Matei Zaharia, 2010) made it faster by keeping data in memory.",
  n:"The same distributed-systems thinking now splits AI training across tens of thousands of GPUs.", src:["Dean & Ghemawat (2008) — MapReduce", "https://doi.org/10.1145/1327452.1327492"] },

// ---------------- Information theory ----------------
"infotheory|Entropy & the bit":{ i:"Information is measured by surprise. A source's entropy, H = −Σ p log₂ p bits per symbol, is the minimum average number of yes/no questions needed to describe its output.",
  s:"Claude Shannon's 1948 'A Mathematical Theory of Communication' defined entropy and channel capacity and adopted John Tukey's word 'bit'.",
  n:"Every compression format rests on it, and the cross-entropy loss that trains language models is Shannon's measure.", src:["Shannon (1948)", "https://doi.org/10.1002/j.1538-7305.1948.tb01338.x"] },
"infotheory|KL divergence / cross-entropy":{ i:"KL divergence measures the extra bits you waste by coding data from one distribution with a code built for another; cross-entropy is entropy plus that waste.",
  s:"Solomon Kullback and Richard Leibler introduced the divergence in 1951, while working on codebreaking-related statistics at the US National Security Agency.",
  n:"Training a classifier or language model minimises cross-entropy; KL penalties keep RLHF-tuned models close to their originals.", src:["Kullback & Leibler (1951) — On Information and Sufficiency", "https://doi.org/10.1214/aoms/1177729694"] },
"infotheory|Kolmogorov complexity":{ i:"The information in a single object is the length of the shortest program that prints it. A random string has no shorter description than itself.",
  s:"Ray Solomonoff (1960–64), Andrey Kolmogorov (1965) and Gregory Chaitin (1966) found the idea independently. It is uncomputable, a cousin of the halting problem.",
  n:"It formalises Occam's razor, and underlies the minimum description length principle and the view of learning as compression.", src:["Li & Vitányi — An Introduction to Kolmogorov Complexity", "https://link.springer.com/book/10.1007/978-3-030-11298-1"] },
"infotheory|Error-correcting codes":{ i:"Add carefully structured redundant bits so that errors can be detected and corrected without resending.",
  s:"Richard Hamming, tired of weekend jobs failing on Bell Labs' relay computers, invented Hamming codes in 1947–50. Shannon had proved near-perfect codes exist; finding practical ones took until turbo codes (1993) and LDPC codes.",
  n:"Error correction protects every phone call, Wi-Fi packet, QR code, disk drive and deep-space probe. See the Hamming(7,4) lab in this guide.", src:["Hamming (1950) — Error Detecting and Error Correcting Codes", "https://doi.org/10.1002/j.1538-7305.1950.tb00463.x"] },

// ---------------- Classical crypto ----------------
"classic-crypto|Enigma":{ i:"An electromechanical rotor cipher machine: each key press sends current through a plugboard, three rotors and a reflector, and the rotors step, so the substitution changes with every letter.",
  s:"Arthur Scherbius patented it in 1918 for commercial use; the German military adopted and strengthened it. About 40,000 were built.",
  n:"The playable Enigma atom uses the historical rotor wirings. Its design flaw (no letter encrypts to itself) is what the Bombe exploited.", src:["Crypto Museum — Enigma", "https://www.cryptomuseum.com/crypto/enigma/"] },
"classic-crypto|Breaking Enigma":{ i:"Mathematics, stolen documents, operator errors and machines combined to read Enigma traffic throughout the war.",
  s:"Polish mathematicians Marian Rejewski, Jerzy Różycki and Henryk Zygalski broke Enigma in 1932 using permutation theory and handed their work to Britain and France in July 1939. Turing and Welchman then scaled it up at Bletchley Park.",
  n:"The Polish contribution was little known until the 1970s. Historians estimate the intelligence shortened the war, perhaps by years.", src:["Bletchley Park — the Polish codebreakers", "https://bletchleypark.org.uk/"] },
"classic-crypto|Perfect secrecy":{ i:"A cipher is perfectly secret if the ciphertext reveals nothing at all about the message. The one-time pad achieves this, provided the key is truly random, as long as the message, and never reused.",
  s:"Shannon proved it in a classified 1945 report published in 1949 as 'Communication Theory of Secrecy Systems', putting cryptography on a mathematical footing.",
  n:"Reusing a one-time pad is fatal: the US Venona project read Soviet messages because some pads were reused.", src:["Shannon (1949) — Communication Theory of Secrecy Systems", "https://doi.org/10.1002/j.1538-7305.1949.tb00928.x"] },

// ---------------- Modern crypto ----------------
"modern-crypto|Public-key cryptography":{ i:"Two strangers can agree a secret key over a public channel, and anyone can encrypt to you with a public key that only your private key can undo.",
  s:"Diffie and Hellman published 'New Directions in Cryptography' in 1976. GCHQ's James Ellis, Clifford Cocks and Malcolm Williamson had found the same ideas secretly in 1970–74.",
  n:"Every HTTPS connection, messaging app and software update relies on it.", src:["Diffie & Hellman (1976)", "https://doi.org/10.1109/TIT.1976.1055638"] },
"modern-crypto|RSA":{ i:"Encryption based on the fact that multiplying two large primes is easy but factoring their product seems to be very hard.",
  s:"Ron Rivest, Adi Shamir and Leonard Adleman invented it at MIT in 1977; Martin Gardner's Scientific American column made it famous with a cash challenge.",
  n:"RSA is being phased out in favour of elliptic-curve and post-quantum schemes, since Shor's algorithm would break it.", src:["Rivest, Shamir & Adleman (1978)", "https://doi.org/10.1145/359340.359342"] },
"modern-crypto|Zero-knowledge proofs":{ i:"Prove that you know something (a password, a solution) without revealing anything about it beyond the fact that it's true.",
  s:"Shafi Goldwasser, Silvio Micali and Charles Rackoff introduced them in 1985. Goldwasser and Micali received the 2012 Turing Award.",
  n:"Zero-knowledge proofs secure blockchain transactions and privacy-preserving identity checks, and are proposed for verifying AI computations.", src:["Goldwasser, Micali & Rackoff (1989) — The Knowledge Complexity of Interactive Proof Systems", "https://doi.org/10.1137/0218012"] },
"modern-crypto|Post-quantum (lattices)":{ i:"Cryptography based on problems, such as finding short vectors in high-dimensional lattices, that seem hard even for quantum computers.",
  s:"Oded Regev introduced learning with errors (LWE) in 2005 and received the 2018 Gödel Prize. NIST standardised the lattice-based ML-KEM (Kyber) and ML-DSA (Dilithium) in 2024.",
  n:"Browsers and messaging apps are already deploying post-quantum key exchange to protect against 'harvest now, decrypt later'.", src:["NIST — Post-Quantum Cryptography", "https://csrc.nist.gov/projects/post-quantum-cryptography"] },

// ---------------- Databases ----------------
"databases|Relational model":{ i:"Store data in tables and query it declaratively with relational algebra, so storage can change without breaking queries.",
  s:"Edgar F. Codd proposed it at IBM in 1970; IBM was slow to adopt it, and Oracle shipped the first commercial SQL database.",
  n:"PostgreSQL, MySQL, SQLite and every major commercial database implement it.", src:["Codd (1970)", "https://doi.org/10.1145/362384.362685"] },
"databases|SQL":{ i:"A declarative language for asking relational databases questions: SELECT, FROM, WHERE, JOIN, GROUP BY.",
  s:"Donald Chamberlin and Raymond Boyce designed SEQUEL for IBM's System R in 1974; it became an ANSI standard in 1986.",
  n:"SQL is among the most used programming languages, and language models are often asked to write it.", src:["Chamberlin & Boyce (1974) — SEQUEL", "https://doi.org/10.1145/800296.811515"] },
"databases|Vector databases":{ i:"Databases that store embeddings and find the ones nearest to a query, using approximate indexes to search billions of vectors quickly.",
  s:"Product quantisation (Jégou et al., 2011), FAISS (2017) and HNSW graphs (2016) made billion-scale similarity search practical; the LLM boom made it a product category.",
  n:"They power retrieval-augmented generation, semantic search and recommendation.", src:["Johnson, Douze & Jégou (2017) — Billion-scale similarity search with GPUs", "https://arxiv.org/abs/1702.08734"] },

// ---------------- Statistics ----------------
"stats|Bayes' theorem":{ i:"Update your belief in a hypothesis by weighing how well it predicts the evidence: posterior ∝ likelihood × prior.",
  s:"Thomas Bayes's essay was published posthumously by Richard Price in 1763; Laplace developed the method independently and applied it widely.",
  n:"Bayesian inference runs spam filters, medical diagnosis and simulation-based inference in cosmology.", src:["Bayes (1763) — An Essay towards Solving a Problem in the Doctrine of Chances", "https://doi.org/10.1098/rstl.1763.0053"] },
"stats|Least squares":{ i:"Fit a model to noisy data by minimising the sum of squared errors, which has a clean closed-form solution.",
  s:"Legendre published it in 1805; Gauss claimed to have used it since 1795, including to predict where the dwarf planet Ceres would reappear in 1801.",
  n:"Linear regression is taught to every scientist, and squared-error loss trains many neural networks.", src:["Stigler (1981) — Gauss and the Invention of Least Squares", "https://doi.org/10.1214/aos/1176345451"] },
"stats|Maximum likelihood":{ i:"Choose the parameters that make the observed data most probable.",
  s:"R. A. Fisher set out the principle in 1912–1922, along with the ideas of sufficiency and efficiency.",
  n:"Training with cross-entropy is maximum likelihood; so is pre-training a language model.", src:["Fisher (1922)", "https://doi.org/10.1098/rsta.1922.0009"] },
"stats|MCMC":{ i:"Sample from a complicated probability distribution with a random walk designed to spend time in each region in proportion to its probability.",
  s:"Metropolis, the Rosenbluths and the Tellers published the method from Los Alamos in 1953; Hastings generalised it in 1970, and it transformed Bayesian statistics around 1990.",
  n:"Stan, PyMC and cosmological and astrophysical parameter estimation rely on it.", src:["Metropolis et al. (1953)", "https://doi.org/10.1063/1.1699114"] },
"stats|Conformal prediction":{ i:"Wrap any model's predictions in intervals with a guaranteed coverage rate, using only held-out calibration data and no distributional assumptions.",
  s:"Vladimir Vovk, Alexander Gammerman and Glenn Shafer developed it from 1999; it became widely used around 2020.",
  n:"It adds trustworthy uncertainty to medical, astronomical and language-model predictions.", src:["Angelopoulos & Bates — A Gentle Introduction to Conformal Prediction", "https://arxiv.org/abs/2107.07511"] },

// ---------------- Practice ----------------
"practice|Exploratory data analysis":{ i:"Look at data with simple plots and summaries before modelling it, to find structure, errors and surprises.",
  s:"John Tukey championed it from his 1962 'The Future of Data Analysis' to his 1977 book, inventing the box plot along the way.",
  n:"Every good analysis still starts here; Anscombe's quartet shows why.", src:["Tukey (1962) — The Future of Data Analysis", "https://doi.org/10.1214/aoms/1177704711"] },
"practice|Notebooks (Jupyter)":{ i:"Documents that mix runnable code, results, plots and explanation, so analyses can be read and rerun.",
  s:"Fernando Pérez started IPython in 2001 as a physics graduate student; the notebook came in 2011 and Project Jupyter in 2014.",
  n:"Jupyter is standard in data science and research teaching, though out-of-order execution remains a reproducibility trap.", src:["Kluyver et al. (2016) — Jupyter Notebooks", "https://doi.org/10.3233/978-1-61499-649-1-87"] },
"practice|'Data science' coined":{ i:"A job title for the mix of statistics, programming and domain expertise needed to learn from large datasets.",
  s:"DJ Patil and Jeff Hammerbacher used it around 2008 for their teams at LinkedIn and Facebook; Harvard Business Review called it 'the sexiest job of the 21st century' in 2012.",
  n:"Statisticians note the field is largely statistics under a new name, a point David Donoho made in '50 Years of Data Science'.", src:["Donoho (2017) — 50 Years of Data Science", "https://doi.org/10.1080/10618600.2017.1384734"] },

// ---------------- Founding documents ----------------
"founding|Computing Machinery and Intelligence":{ i:"Replace 'can machines think?' with a test: can a machine converse so that an interrogator can't reliably tell it from a person?",
  s:"Turing's 1950 paper in the philosophy journal Mind also answered nine objections and proposed educating a 'child machine' by learning.",
  n:"Language models now pass short versions of the game, reopening the debate about what the test measures.", src:["Turing (1950)", "https://doi.org/10.1093/mind/LIX.236.433"] },
"founding|Dartmouth workshop":{ i:"A summer study proposing that every aspect of intelligence can be described precisely enough for a machine to simulate it.",
  s:"McCarthy, Minsky, Rochester and Shannon wrote the proposal in 1955, coining 'artificial intelligence'; the workshop ran in summer 1956.",
  n:"It is AI's official birthday, and its list of topics (language, neural nets, self-improvement) reads like today's research agenda.", src:["The Dartmouth proposal (1955)", "http://jmc.stanford.edu/articles/dartmouth/dartmouth.pdf"] },
"founding|Logic Theorist":{ i:"A program that proved theorems of logic by heuristic search, working backwards from the goal as a mathematician does.",
  s:"Newell, Simon and Cliff Shaw built it in 1955–56; it proved 38 of the first 52 theorems of Principia Mathematica.",
  n:"Heuristic search became symbolic AI's central method, and AI theorem proving is now a frontier again.", src:["Newell & Simon (1956)", "https://doi.org/10.1109/TIT.1956.1056797"] },

// ---------------- Symbolic AI ----------------
"symbolic|Minimax & alpha-beta":{ i:"Look ahead through a game's moves, assuming both sides play their best, and prune branches that can't change the decision.",
  s:"Minimax comes from von Neumann's 1928 theorem; Shannon's 1950 chess paper applied it to computers, and alpha–beta pruning was developed in the 1950s and analysed by Knuth and Moore in 1975.",
  n:"Classical chess engines still use alpha–beta, now paired with small neural networks for evaluation.", src:["Knuth & Moore (1975)", "https://doi.org/10.1016/0004-3702(75)90019-3"] },
"symbolic|Expert systems (MYCIN)":{ i:"Programs that encode human expertise as hundreds of if–then rules and reason with them, explaining their conclusions.",
  s:"MYCIN (Stanford, 1970s) diagnosed blood infections as well as specialists in a 1979 evaluation but was never used clinically. DEC's XCON saved millions configuring computers; the boom collapsed in the late 1980s.",
  n:"Rule systems survive in tax software and clinical decision support; MYCIN's explanations inspired explainable AI.", src:["Buchanan & Shortliffe (1984) — Rule-Based Expert Systems", "https://www.shortliffe.net/Buchanan-Shortliffe-1984/MYCIN%20Book.htm"] },
"symbolic|Prolog":{ i:"Program by stating facts and rules in logic; the system answers queries by logical inference.",
  s:"Alain Colmerauer and Philippe Roussel created Prolog in Marseille in 1972 with Robert Kowalski; Japan's Fifth Generation project bet on it in the 1980s.",
  n:"Its descendant Datalog runs in program analysis and security tools, and logic rules are returning in neurosymbolic AI.", src:["Colmerauer & Roussel (1993) — The Birth of Prolog", "https://doi.org/10.1145/154766.155362"] },
"symbolic|ELIZA":{ i:"A chatbot that imitated a psychotherapist with pattern matching and pronoun swapping, understanding nothing.",
  s:"Joseph Weizenbaum wrote it at MIT in 1966. Disturbed by how readily people confided in it, he wrote 'Computer Power and Human Reason' (1976).",
  n:"The 'ELIZA effect' (reading understanding into fluent text) is stronger than ever with modern chatbots.", src:["Weizenbaum (1966)", "https://doi.org/10.1145/365153.365168"] },

// ---------------- Milestones ----------------
"milestones|Deep Blue beats Kasparov":{ i:"A chess computer beats the reigning world champion in a match under tournament conditions, using massive search and a hand-tuned evaluation.",
  s:"IBM's Deep Blue lost to Kasparov 4–2 in 1996 and won the 1997 rematch 3½–2½ in New York.",
  n:"The map calls it the high-water mark of search-based AI, before learning (AlphaZero) took over.", src:["Campbell, Hoane & Hsu (2002) — Deep Blue", "https://doi.org/10.1016/S0004-3702(01)00129-1"] },
"milestones|Watson wins Jeopardy!":{ i:"A question-answering system combining hundreds of statistical evidence scorers beats the two greatest Jeopardy! champions.",
  s:"IBM's DeepQA team, led by David Ferrucci, won the televised match in February 2011; its 'Toronto' answer in the U.S. Cities category became famous.",
  n:"Watson Health's later struggles became a standard lesson that demos are not deployment.", src:["Ferrucci et al. (2010) — Building Watson", "https://doi.org/10.1609/aimag.v31i3.2303"] },

// ---------------- Decision theory ----------------
"decision|Game theory":{ i:"The mathematics of strategic interaction, where each player's best choice depends on the others'.",
  s:"Von Neumann proved the minimax theorem in 1928 and, with Morgenstern, wrote 'Theory of Games and Economic Behavior' (1944); Nash's equilibrium (1950) extended it to all finite games.",
  n:"It underpins auction design, poker AI and multi-agent AI safety research.", src:["Nash (1950) — Equilibrium Points in n-Person Games", "https://doi.org/10.1073/pnas.36.1.48"] },
"decision|Markov decision processes":{ i:"States, actions, probabilistic transitions and rewards: the formal model of sequential decision-making.",
  s:"Richard Bellman formalised MDPs and dynamic programming for them at RAND in 1957; Ronald Howard's policy iteration followed in 1960.",
  n:"Every reinforcement learning algorithm, including RLHF, is written in the language of MDPs.", src:["Bellman (1957) — A Markovian Decision Process", "https://www.jstor.org/stable/24900506"] },
"decision|Multi-agent systems":{ i:"Many autonomous agents, each with its own goals and knowledge, cooperating, competing or negotiating.",
  s:"Distributed AI grew in the 1980s (contract nets, 1980; BDI agents, late 1980s); Axelrod's tournaments (1980) studied cooperation between strategies.",
  n:"LLM agent teams are revisiting this literature on coordination, negotiation and incentives.", src:["Axelrod & Hamilton (1981) — The Evolution of Cooperation", "https://doi.org/10.1126/science.7466396"] },

// ---------------- Neural prehistory ----------------
"prehistory|McCulloch–Pitts neuron":{ i:"The first mathematical model of a neuron: a threshold unit computing logic.",
  s:"Warren McCulloch and the teenage Walter Pitts published it in 1943.",
  n:"Every artificial neuron is its descendant: a weighted sum followed by a nonlinearity.", src:["McCulloch & Pitts (1943)", "https://doi.org/10.1007/BF02478259"] },
"prehistory|Hebbian learning":{ i:"Strengthen connections between neurons that are active together: learning from correlation, with no teacher.",
  s:"Psychologist Donald Hebb proposed it in 'The Organization of Behavior' (1949).",
  n:"It inspired Hopfield networks and remains a model of biological learning.", src:["Hebb (1949)", "https://doi.org/10.4324/9781410612403"] },
"prehistory|Perceptron":{ i:"A trainable threshold neuron that adjusts its weights after each mistake and provably learns any linearly separable pattern.",
  s:"Frank Rosenblatt built the Mark I Perceptron in 1958; the press called it the embryo of a conscious machine.",
  n:"It is the first learning algorithm most students meet, and the ancestor of every classifier's final layer.", src:["Rosenblatt (1958)", "https://doi.org/10.1037/h0042519"] },
"prehistory|Perceptrons (the book)":{ i:"A rigorous analysis of what single-layer perceptrons can't compute, including XOR and connectedness.",
  s:"Minsky and Papert published it in 1969; funding for neural networks dried up for more than a decade.",
  n:"A correct theorem about a limited model was read as a verdict on the whole approach, a cautionary tale for today's debates.", src:["Minsky & Papert — Perceptrons", "https://mitpress.mit.edu/9780262630221/perceptrons/"] },
"prehistory|Backpropagation":{ i:"Compute every weight's contribution to the error by applying the chain rule backwards through the network.",
  s:"Linnainmaa (1970) described reverse-mode differentiation, Werbos (1974) applied it to networks, and Rumelhart, Hinton and Williams's 1986 Nature paper made it famous.",
  n:"Every neural network is trained by backprop, computed automatically by PyTorch and JAX.", src:["Rumelhart, Hinton & Williams (1986)", "https://doi.org/10.1038/323533a0"] },

// ---------------- Classical ML ----------------
"classical|k-nearest neighbors":{ i:"Classify a new point by a vote of the k labelled points nearest to it.",
  s:"Fix and Hodges described it in a 1951 US Air Force report; Cover and Hart proved its error bound in 1967.",
  n:"Nearest-neighbour search over embeddings is how vector databases and RAG work.", src:["Cover & Hart (1967)", "https://doi.org/10.1109/TIT.1967.1053964"] },
"classical|k-means":{ i:"Group unlabelled points into k clusters by alternately assigning points to the nearest centre and moving each centre to its points' mean.",
  s:"Stuart Lloyd devised it at Bell Labs in 1957; it was published only in 1982.",
  n:"It compresses colours and embeddings, segments customers and builds vector-index codebooks.", src:["Lloyd (1982)", "https://doi.org/10.1109/TIT.1982.1056489"] },
"classical|Decision trees & random forests":{ i:"Split data with yes/no questions; average many randomised trees to reduce overfitting.",
  s:"Breiman, Friedman, Olshen and Stone published CART in 1984; Breiman introduced random forests in 2001.",
  n:"Tree ensembles still beat deep learning on most tabular data.", src:["Breiman (2001) — Random Forests", "https://doi.org/10.1023/A:1010933404324"] },
"classical|SVMs & kernel methods":{ i:"Find the boundary with the widest margin between classes, and use kernels to draw curved boundaries in very high-dimensional spaces.",
  s:"Boser, Guyon and Vapnik (1992) and Cortes and Vapnik (1995); SVMs dominated machine learning until about 2012.",
  n:"Kernels live on in Gaussian processes and in theories of very wide neural networks.", src:["Cortes & Vapnik (1995)", "https://doi.org/10.1007/BF00994018"] },
"classical|Gradient boosting / XGBoost":{ i:"Add small trees one at a time, each fitted to the current model's errors: gradient descent in function space.",
  s:"Freund and Schapire's AdaBoost (1995), Friedman's gradient boosting (2001), and Chen and Guestrin's XGBoost (2014).",
  n:"It wins many tabular competitions and runs much of industrial credit scoring and forecasting.", src:["Chen & Guestrin (2016) — XGBoost", "https://arxiv.org/abs/1603.02754"] },
"classical|PCA / t-SNE / UMAP":{ i:"Squash high-dimensional data into two or three dimensions to see it: linearly (PCA) or by preserving neighbourhoods (t-SNE, UMAP).",
  s:"Karl Pearson invented PCA in 1901; van der Maaten and Hinton published t-SNE in 2008; McInnes and colleagues UMAP in 2018.",
  n:"They are the standard way to look at embeddings and single-cell biology data.", src:["Pearson (1901)", "https://doi.org/10.1080/14786440109462720"] },
"classical|Bias–variance → double descent":{ i:"Test error first falls then rises as models grow (the classical U-curve), but can fall again past the point where the model fits the data exactly.",
  s:"Geman, Bienenstock and Doursat formalised the bias–variance dilemma in 1992; Belkin and colleagues named double descent in 2019.",
  n:"Explaining why huge networks generalise is an open theoretical problem.", src:["Belkin et al. (2019)", "https://doi.org/10.1073/pnas.1903070116"] },

// ---------------- Learning paradigms ----------------
"paradigms-ml|Supervised learning":{ i:"Learn a mapping from inputs to outputs from labelled examples.",
  s:"From the perceptron (1958) through SVMs and deep nets, it has been machine learning's workhorse; ImageNet's labels (2009) enabled deep learning's breakthrough.",
  n:"Supervised fine-tuning adapts foundation models to specific tasks.", src:["Hastie, Tibshirani & Friedman — Elements of Statistical Learning", "https://hastie.su.domains/ElemStatLearn/"] },
"paradigms-ml|Unsupervised learning":{ i:"Find structure (clusters, directions, distributions) in data without labels.",
  s:"Clustering (Lloyd, 1957), PCA and autoencoders (Hinton & Salakhutdinov, 2006) are its classics.",
  n:"Generative models are unsupervised learning at scale: they model the data distribution itself.", src:["Hinton & Salakhutdinov (2006)", "https://doi.org/10.1126/science.1127647"] },
"paradigms-ml|Reinforcement learning":{ i:"Learn to act from rewards received after acting, often long delayed.",
  s:"Sutton's temporal-difference learning (1988) and Watkins's Q-learning (1989) founded modern RL; Sutton and Barto received the 2024 Turing Award.",
  n:"RL trains game champions and robots and shapes language models through RLHF and reasoning training.", src:["Sutton & Barto — Reinforcement Learning: An Introduction", "http://incompleteideas.net/book/the-book.html"] },
"paradigms-ml|Self-supervised learning":{ i:"Supervised learning with labels made from the data itself: predict the next word, a masked word or a hidden image patch.",
  s:"word2vec (2013), BERT (2018) and SimCLR (2020) showed its power; GPT's next-token prediction is self-supervised.",
  n:"Almost every foundation model is pre-trained self-supervised.", src:["Devlin et al. (2018) — BERT", "https://arxiv.org/abs/1810.04805"] },

// ---------------- Deep learning ----------------
"deep|CNNs (Neocognitron → LeNet)":{ i:"Networks that slide small learned filters across an image, sharing weights, so they recognise a pattern wherever it appears.",
  s:"Fukushima's Neocognitron (1980) had the architecture; LeCun trained it with backprop in 1989, reading zip codes and later cheques.",
  n:"CNNs still run much of computer vision on phones, cameras and medical scanners.", src:["LeCun et al. (1998) — Gradient-Based Learning Applied to Document Recognition", "https://doi.org/10.1109/5.726791"] },
"deep|AlexNet":{ i:"A deep CNN trained on two GPUs that cut ImageNet's top-5 error from about 26% to 15% in 2012.",
  s:"Krizhevsky, Sutskever and Hinton; ReLU, dropout and CUDA made it possible. Google bought their company within months.",
  n:"It is the opening bell of the deep learning era.", src:["Krizhevsky, Sutskever & Hinton (2017, CACM)", "https://doi.org/10.1145/3065386"] },
"deep|LSTM":{ i:"A recurrent network with gated memory cells that let information and gradients persist over long sequences.",
  s:"Hochreiter and Schmidhuber published it in 1997; it powered speech recognition and translation from about 2015.",
  n:"Transformers mostly replaced it, but recurrence is returning in state-space models and xLSTM.", src:["Hochreiter & Schmidhuber (1997)", "https://doi.org/10.1162/neco.1997.9.8.1735"] },
"deep|word2vec":{ i:"Learn a vector for every word so that words used in similar contexts are close, and relationships become directions.",
  s:"Tomas Mikolov and colleagues at Google published it in 2013; king − man + woman ≈ queen became famous.",
  n:"Every language model begins with an embedding table, and embeddings power semantic search.", src:["Mikolov et al. (2013)", "https://arxiv.org/abs/1301.3781"] },
"deep|GANs":{ i:"Train a generator and a discriminator against each other until generated data is hard to tell from real.",
  s:"Ian Goodfellow proposed GANs in 2014; StyleGAN (2019) made photorealistic faces.",
  n:"Diffusion models have largely replaced GANs for images.", src:["Goodfellow et al. (2014)", "https://arxiv.org/abs/1406.2661"] },
"deep|Transformer — 'Attention Is All You Need'":{ i:"An architecture built only from attention (each token weighs every other token) plus small feed-forward layers, trainable in parallel.",
  s:"Vaswani, Shazeer, Parmar and colleagues at Google introduced it in 2017 for translation.",
  n:"It underlies GPT, Claude, Gemini, AlphaFold 2 and most modern AI.", src:["Vaswani et al. (2017)", "https://arxiv.org/abs/1706.03762"] },
"deep|Diffusion models":{ i:"Generate data by learning to reverse a process that gradually turns data into noise.",
  s:"Sohl-Dickstein and colleagues introduced the idea from physics in 2015; Ho, Jain and Abbeel's DDPM (2020) and latent diffusion (2022) made it dominant.",
  n:"Most AI image and video generators are diffusion models.", src:["Ho, Jain & Abbeel (2020)", "https://arxiv.org/abs/2006.11239"] },
"deep|KANs":{ i:"Networks whose edges carry learnable one-variable functions instead of fixed weights, inspired by the Kolmogorov–Arnold representation theorem.",
  s:"Liu and colleagues proposed Kolmogorov–Arnold networks in 2024; physicists quickly built physics-informed variants.",
  n:"Promising for interpretable scientific modelling, still unproven at scale.", src:["Liu et al. (2024) — KAN", "https://arxiv.org/abs/2404.19756"] },

// ---------------- LLM era ----------------
"llm|Scaling laws":{ i:"Language-model loss falls as a smooth power law in parameters, data and compute, so bigger training runs can be planned in advance.",
  s:"Kaplan and colleagues (2020) measured the laws; Hoffmann and colleagues' Chinchilla (2022) showed data should grow as fast as model size.",
  n:"Scaling laws turned AI progress into a question of compute and data budgets.", src:["Kaplan et al. (2020)", "https://arxiv.org/abs/2001.08361"] },
"llm|GPT-3 → ChatGPT":{ i:"A 175-billion-parameter model that learns new tasks from examples in its prompt, then a chat interface that put it in everyone's hands.",
  s:"GPT-3 appeared in 2020; ChatGPT launched on 30 November 2022 and reached an estimated 100 million users in about two months.",
  n:"It started the current AI race.", src:["Brown et al. (2020) — Language Models are Few-Shot Learners", "https://arxiv.org/abs/2005.14165"] },
"llm|RLHF":{ i:"Learn a reward model from human comparisons of answers, then fine-tune the language model with reinforcement learning to score well on it.",
  s:"Christiano and colleagues (2017) introduced learning from human preferences; InstructGPT (2022) applied it to language.",
  n:"Every major chat assistant is shaped by preference training.", src:["Christiano et al. (2017)", "https://arxiv.org/abs/1706.03741"] },
"llm|Constitutional AI":{ i:"Train a model to be helpful and harmless using a written set of principles and AI-generated feedback.",
  s:"Anthropic published it in 2022.",
  n:"Written principles and AI feedback are now widely used across the industry.", src:["Bai et al. (2022)", "https://arxiv.org/abs/2212.08073"] },
"llm|Interpretability (circuits, SAEs)":{ i:"Reverse-engineer what networks compute, finding circuits and interpretable features inside them.",
  s:"Olah and colleagues' circuits work (2020), transformer circuits (2021), and sparse autoencoders ('Towards Monosemanticity', 2023).",
  n:"A young, fast-moving field central to AI safety.", src:["Bricken et al. (2023) — Towards Monosemanticity", "https://transformer-circuits.pub/2023/monosemantic-features/index.html"] },
"llm|The Bitter Lesson":{ i:"General methods that scale with computation (search and learning) eventually beat methods that build in human knowledge.",
  s:"Richard Sutton's one-page essay, March 2019.",
  n:"The unofficial creed of the scaling era, and much debated.", src:["Sutton (2019) — The Bitter Lesson", "http://www.incompleteideas.net/IncIdeas/BitterLesson.html"] },

// ---------------- Deep RL ----------------
"deeprl|DQN (Atari)":{ i:"A deep network learns to play Atari games from pixels and score alone, using Q-learning with experience replay.",
  s:"DeepMind's Mnih and colleagues published it in 2013 and in Nature in 2015; Google bought DeepMind in 2014.",
  n:"It proved deep learning and reinforcement learning could be combined.", src:["Mnih et al. (2015)", "https://doi.org/10.1038/nature14236"] },
"deeprl|AlphaGo":{ i:"Tree search guided by policy and value networks beats a top Go professional.",
  s:"AlphaGo beat Lee Sedol 4–1 in Seoul in March 2016; Move 37 of game 2 became famous.",
  n:"AlphaZero and MuZero generalised it, and pros now study with AI.", src:["Silver et al. (2016)", "https://doi.org/10.1038/nature16961"] },
"deeprl|AlphaFold":{ i:"Predict a protein's 3-D structure from its amino-acid sequence with near-experimental accuracy.",
  s:"AlphaFold 2 won CASP14 in 2020; Hassabis and Jumper shared the 2024 Nobel Prize in Chemistry.",
  n:"Over 200 million predicted structures are freely available to researchers.", src:["Jumper et al. (2021)", "https://doi.org/10.1038/s41586-021-03819-2"] }
};
